name: chatapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  device_preview: ^1.1.0
  flutter_easyloading: ^3.0.5
  pretty_dio_logger: ^1.3.1
  dio: ^5.3.4
  equatable: ^2.0.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.2.2
  extended_image: ^8.2.0
  iconsax_flutter: ^1.0.0
  signalr_netcore: ^1.3.7
  cupertino_icons: ^1.0.2
  event_bus: ^2.0.0
  firebase_core: ^2.15.0
  firebase_core_platform_interface: ^4.8.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.6.5
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.5.1



dev_dependencies:
  flutter_gen: ^5.3.2
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.2
  json_serializable: ^6.7.1



flutter:


  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    - assets/icons/
#    - assets/animations/